(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e" "-f"
"-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z" "abs" "accept"
"alarm" "atan2" "bind" "binmode" "bless" "break" "caller" "chdir" "chmod"
"chomp" "chop" "chown" "chr" "chroot" "close" "closedir" "connect"
"continue" "cos" "crypt" "dbmclose" "dbmopen" "defined" "delete" "die" "do"
"dump" "each" "endgrent" "endhostent" "endnetent" "endprotoent" "endpwent"
"endservent" "eof" "eval" "exec" "exists" "exit" "exp" "fcntl" "fileno"
"flock" "fork" "format" "formline" "getc" "getgrent" "getgrgid" "getgrnam"
"gethostbyaddr" "gethostbyname" "gethostent" "getlogin" "getnetbyaddr"
"getnetbyname" "getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar"
"seek" "seekdir" "select" "semctl" "semget" "semop" "send" "setgrent"
"sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent"
"setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite"
"shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice" "split"
"sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink"
"syscall" "sysopen" "sysread" "sysseek" "system" "syswrite" "tell"
"telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"AnyDBM_File" "App::Prove" "App::Prove::State" "App::Prove::State::Result"
"App::Prove::State::Result::Test" "Archive::Extract" "Archive::Tar"
"Archive::Tar::Constant" "Archive::Tar::File" "Attribute::Handlers"
"AutoLoader" "AutoSplit" "B" "B::Concise" "B::Debug" "B::Deparse" "B::Lint"
"B::Lint::Debug" "B::Showlex" "B::Terse" "B::Xref" "BSDPAN"
"BSDPAN::BSDPAN" "BSDPAN::BSDPAN::Override" "BSDPAN::Config"
"BSDPAN::ExtUtils::MM_Unix" "BSDPAN::ExtUtils::MakeMaker"
"BSDPAN::ExtUtils::Packlist" "BSDPAN::Override" "Benchmark"
"Bundle::DBD::mysql" "Bundle::DBI" "CGI" "CGI::Apache" "CGI::Carp"
"CGI::Cookie" "CGI::Fast" "CGI::Pretty" "CGI::Push" "CGI::Switch"
"CGI::Util" "CORE" "CPAN" "CPAN::API::HOWTO" "CPAN::Author" "CPAN::Bundle"
"CPAN::CacheMgr" "CPAN::Complete" "CPAN::Debug" "CPAN::DeferredCode"
"CPAN::Distribution" "CPAN::Distroprefs" "CPAN::Distrostatus"
"CPAN::Exception::RecursiveDependency" "CPAN::Exception::blocked_urllist"
"CPAN::Exception::yaml_not_installed" "CPAN::FTP" "CPAN::FTP::netrc"
"CPAN::FirstTime" "CPAN::HandleConfig" "CPAN::Index" "CPAN::InfoObj"
"CPAN::Kwalify" "CPAN::LWP::UserAgent" "CPAN::Module" "CPAN::Nox"
"CPAN::Prompt" "CPAN::Queue" "CPAN::Shell" "CPAN::Tarzip" "CPAN::URL"
"CPAN::Version" "CPANPLUS" "CPANPLUS::Backend" "CPANPLUS::Backend::RV"
"CPANPLUS::Config" "CPANPLUS::Configure" "CPANPLUS::Configure::Setup"
"CPANPLUS::Dist" "CPANPLUS::Dist::Autobundle" "CPANPLUS::Dist::Base"
"CPANPLUS::Dist::Build" "CPANPLUS::Dist::Build::Constants"
"CPANPLUS::Dist::MM" "CPANPLUS::Dist::Sample" "CPANPLUS::Error"
"CPANPLUS::FAQ" "CPANPLUS::Hacking" "CPANPLUS::Internals"
"CPANPLUS::Internals::Constants" "CPANPLUS::Internals::Constants::Report"
"CPANPLUS::Internals::Extract" "CPANPLUS::Internals::Fetch"
"CPANPLUS::Internals::Report" "CPANPLUS::Internals::Search"
"CPANPLUS::Internals::Source" "CPANPLUS::Internals::Source::Memory"
"CPANPLUS::Internals::Source::SQLite"
"CPANPLUS::Internals::Source::SQLite::Tie" "CPANPLUS::Internals::Utils"
"CPANPLUS::Internals::Utils::Autoflush" "CPANPLUS::Module"
"CPANPLUS::Module::Author" "CPANPLUS::Module::Author::Fake"
"CPANPLUS::Module::Checksums" "CPANPLUS::Module::Fake"
"CPANPLUS::Module::Signature" "CPANPLUS::Selfupdate" "CPANPLUS::Shell"
"CPANPLUS::Shell::Classic" "CPANPLUS::Shell::Default"
"CPANPLUS::Shell::Default::Plugins::CustomSource"
"CPANPLUS::Shell::Default::Plugins::HOWTO"
"CPANPLUS::Shell::Default::Plugins::Remote"
"CPANPLUS::Shell::Default::Plugins::Source" "Carp" "Carp::Heavy"
"Class::ISA" "Class::Struct" "Compress::Raw::Bzip2" "Compress::Raw::Zlib"
"Compress::Zlib" "Config" "Config::Extensions" "Cwd" "DB" "DBD::DBM"
"DBD::ExampleP" "DBD::File" "DBD::File::Developers" "DBD::File::HowTo"
"DBD::File::Roadmap" "DBD::Gofer" "DBD::Gofer::Policy::Base"
"DBD::Gofer::Policy::classic" "DBD::Gofer::Policy::pedantic"
"DBD::Gofer::Policy::rush" "DBD::Gofer::Transport::Base"
"DBD::Gofer::Transport::null" "DBD::Gofer::Transport::pipeone"
"DBD::Gofer::Transport::stream" "DBD::NullP" "DBD::Proxy" "DBD::Sponge"
"DBD::mysql" "DBD::mysql::GetInfo" "DBD::mysql::INSTALL" "DBI"
"DBI::Changes" "DBI::Const::GetInfo::ANSI" "DBI::Const::GetInfo::ODBC"
"DBI::Const::GetInfoReturn" "DBI::Const::GetInfoType" "DBI::DBD"
"DBI::DBD::Metadata" "DBI::DBD::SqlEngine"
"DBI::DBD::SqlEngine::Developers" "DBI::DBD::SqlEngine::HowTo" "DBI::FAQ"
"DBI::Gofer::Execute" "DBI::Gofer::Request" "DBI::Gofer::Response"
"DBI::Gofer::Serializer::Base" "DBI::Gofer::Serializer::DataDumper"
"DBI::Gofer::Serializer::Storable" "DBI::Gofer::Transport::Base"
"DBI::Gofer::Transport::pipeone" "DBI::Gofer::Transport::stream"
"DBI::Profile" "DBI::ProfileData" "DBI::ProfileDumper"
"DBI::ProfileDumper::Apache" "DBI::ProfileSubs" "DBI::ProxyServer"
"DBI::PurePerl" "DBI::SQL::Nano" "DBI::Util::CacheMemory"
"DBI::Util::_accessor" "DBI::W32ODBC" "DBM_Filter" "DBM_Filter::compress"
"DBM_Filter::encode" "DBM_Filter::int32" "DBM_Filter::null"
"DBM_Filter::utf8" "DB_File" "Data::Dumper" "Devel::DProf"
"Devel::InnerPackage" "Devel::PPPort" "Devel::Peek" "Devel::SelfStubber"
"Digest" "Digest::MD5" "Digest::SHA" "Digest::base" "Digest::file"
"DirHandle" "Dumpvalue" "DynaLoader" "Encode" "Encode::Alias"
"Encode::Byte" "Encode::CJKConstants" "Encode::CN" "Encode::CN::HZ"
"Encode::Config" "Encode::EBCDIC" "Encode::Encoder" "Encode::Encoding"
"Encode::GSM0338" "Encode::Guess" "Encode::JP" "Encode::JP::H2Z"
"Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Error" "Error::Simple" "Exporter" "Exporter::Heavy"
"ExtUtils::CBuilder" "ExtUtils::CBuilder::Base"
"ExtUtils::CBuilder::Platform::Unix" "ExtUtils::CBuilder::Platform::VMS"
"ExtUtils::CBuilder::Platform::Windows" "ExtUtils::CBuilder::Platform::aix"
"ExtUtils::CBuilder::Platform::cygwin"
"ExtUtils::CBuilder::Platform::darwin"
"ExtUtils::CBuilder::Platform::dec_osf" "ExtUtils::CBuilder::Platform::os2"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Embed"
"ExtUtils::Install" "ExtUtils::Installed" "ExtUtils::Liblist"
"ExtUtils::Liblist::Kid" "ExtUtils::MM" "ExtUtils::MM_AIX"
"ExtUtils::MM_Any" "ExtUtils::MM_BeOS" "ExtUtils::MM_Cygwin"
"ExtUtils::MM_DOS" "ExtUtils::MM_Darwin" "ExtUtils::MM_MacOS"
"ExtUtils::MM_NW5" "ExtUtils::MM_OS2" "ExtUtils::MM_QNX"
"ExtUtils::MM_UWIN" "ExtUtils::MM_Unix" "ExtUtils::MM_VMS"
"ExtUtils::MM_VOS" "ExtUtils::MM_Win32" "ExtUtils::MM_Win95" "ExtUtils::MY"
"ExtUtils::MakeMaker" "ExtUtils::MakeMaker::Config"
"ExtUtils::MakeMaker::FAQ" "ExtUtils::MakeMaker::Tutorial"
"ExtUtils::Manifest" "ExtUtils::Miniperl" "ExtUtils::Mkbootstrap"
"ExtUtils::Mksymlists" "ExtUtils::Packlist" "ExtUtils::ParseXS"
"ExtUtils::testlib" "Fatal" "Fcntl" "File::Basename" "File::CheckTree"
"File::Compare" "File::Copy" "File::DosGlob" "File::Fetch" "File::Find"
"File::Glob" "File::GlobMapper" "File::Path" "File::Spec"
"File::Spec::Cygwin" "File::Spec::Epoc" "File::Spec::Functions"
"File::Spec::Mac" "File::Spec::OS2" "File::Spec::Unix" "File::Spec::VMS"
"File::Spec::Win32" "File::Temp" "File::stat" "FileCache" "FileHandle"
"Filter::Simple" "Filter::Util::Call" "FindBin" "Getopt::Long"
"Getopt::Std" "Git" "Hash::Util" "Hash::Util::FieldHash" "I18N::Collate"
"I18N::LangTags" "I18N::LangTags::Detect" "I18N::LangTags::List"
"I18N::Langinfo" "IO" "IO::Compress::Adapter::Bzip2"
"IO::Compress::Adapter::Deflate" "IO::Compress::Adapter::Identity"
"IO::Compress::Base" "IO::Compress::Base::Common" "IO::Compress::Bzip2"
"IO::Compress::Deflate" "IO::Compress::Gzip"
"IO::Compress::Gzip::Constants" "IO::Compress::RawDeflate"
"IO::Compress::Zip" "IO::Compress::Zip::Constants"
"IO::Compress::Zlib::Constants" "IO::Compress::Zlib::Extra" "IO::Dir"
"IO::File" "IO::Handle" "IO::Pipe" "IO::Poll" "IO::Seekable" "IO::Select"
"IO::Socket" "IO::Socket::INET" "IO::Socket::INET6" "IO::Socket::SSL"
"IO::Socket::UNIX" "IO::Uncompress::Adapter::Bunzip2"
"IO::Uncompress::Adapter::Identity" "IO::Uncompress::Adapter::Inflate"
"IO::Uncompress::AnyInflate" "IO::Uncompress::AnyUncompress"
"IO::Uncompress::Base" "IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Zlib" "IPC::Cmd" "IPC::Msg" "IPC::Open2"
"IPC::Open3" "IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "Irssi"
"Irssi::Irc" "Irssi::TextUI" "Irssi::UI" "List::Util" "List::Util::PP"
"List::Util::XS" "Locale::Constants" "Locale::Country" "Locale::Currency"
"Locale::Language" "Locale::Maketext" "Locale::Maketext::Guts"
"Locale::Maketext::GutsLoader" "Locale::Maketext::Simple"
"Locale::Maketext::TPJ13" "Locale::Script" "Locale::gettext" "Log::Message"
"Log::Message::Config" "Log::Message::Handlers" "Log::Message::Item"
"Log::Message::Simple" "MIME::Base64" "MIME::QuotedPrint" "Math::BigFloat"
"Math::BigFloat::Trace" "Math::BigInt" "Math::BigInt::Calc"
"Math::BigInt::CalcEmu" "Math::BigInt::FastCalc" "Math::BigInt::Trace"
"Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "Module::Build" "Module::Build::API"
"Module::Build::Authoring" "Module::Build::Base" "Module::Build::Compat"
"Module::Build::Config" "Module::Build::ConfigData"
"Module::Build::Cookbook" "Module::Build::Dumper"
"Module::Build::ModuleInfo" "Module::Build::Notes"
"Module::Build::PPMMaker" "Module::Build::Platform::Amiga"
"Module::Build::Platform::Default" "Module::Build::Platform::EBCDIC"
"Module::Build::Platform::MPEiX" "Module::Build::Platform::MacOS"
"Module::Build::Platform::RiscOS" "Module::Build::Platform::Unix"
"Module::Build::Platform::VMS" "Module::Build::Platform::VOS"
"Module::Build::Platform::Windows" "Module::Build::Platform::aix"
"Module::Build::Platform::cygwin" "Module::Build::Platform::darwin"
"Module::Build::Platform::os2" "Module::Build::PodParser"
"Module::Build::Version" "Module::Build::YAML" "Module::CoreList"
"Module::Load" "Module::Load::Conditional" "Module::Loaded"
"Module::Pluggable" "Module::Pluggable::Object" "NDBM_File" "NEXT"
"Net::Cmd" "Net::Config" "Net::Domain" "Net::FTP" "Net::FTP::A"
"Net::FTP::E" "Net::FTP::I" "Net::FTP::L" "Net::FTP::dataconn" "Net::NNTP"
"Net::Netrc" "Net::POP3" "Net::Ping" "Net::SMTP" "Net::SMTP::SSL"
"Net::SSLeay" "Net::SSLeay::Handle" "Net::Time" "Net::hostent"
"Net::libnetFAQ" "Net::netent" "Net::protoent" "Net::servent"
"NetSNMP::ASN" "NetSNMP::OID" "NetSNMP::TrapReceiver" "NetSNMP::agent"
"NetSNMP::agent::Support" "NetSNMP::agent::default_store"
"NetSNMP::agent::netsnmp_request_infoPtr" "NetSNMP::default_store" "O"
"Object::Accessor" "Opcode" "POSIX" "Package::Constants" "Params::Check"
"Parse::CPAN::Meta" "PerlIO" "PerlIO::encoding" "PerlIO::scalar"
"PerlIO::via" "PerlIO::via::QuotedPrint" "Pod::Checker" "Pod::Escapes"
"Pod::Find" "Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX"
"Pod::Man" "Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToChecker"
"Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff" "Pod::Perldoc::ToPod"
"Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText" "Pod::Perldoc::ToTk"
"Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Plainer" "Pod::Select"
"Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "RRDp" "RRDs"
"SDBM_File" "SNMP" "Safe" "Scalar::Util" "Scalar::Util::PP" "Search::Dict"
"SelectSaver" "SelfLoader" "Shell" "Socket" "Socket6" "Storable" "Switch"
"Symbol" "Sys::Hostname" "Sys::Syslog" "TAP::Base" "TAP::Formatter::Base"
"TAP::Formatter::Color" "TAP::Formatter::Console"
"TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Object" "TAP::Parser" "TAP::Parser::Aggregator"
"TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::Source::Perl" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer"
"Term::ANSIColor" "Term::Cap" "Term::Complete" "Term::ReadKey"
"Term::ReadLine" "Term::UI" "Term::UI::History" "Test" "Test::Builder"
"Test::Builder::Module" "Test::Builder::Tester"
"Test::Builder::Tester::Color" "Test::Harness" "Test::More" "Test::Simple"
"Test::Tutorial" "Text::Abbrev" "Text::Balanced" "Text::ParseWords"
"Text::Soundex" "Text::Tabs" "Text::Wrap" "Thread" "Thread::Queue"
"Thread::Semaphore" "Tie::Array" "Tie::File" "Tie::Handle" "Tie::Hash"
"Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash" "Tie::Scalar"
"Tie::StdHandle" "Tie::SubstrHash" "Time::HiRes" "Time::Local"
"Time::Piece" "Time::Seconds" "Time::gmtime" "Time::localtime" "Time::tm"
"UNIVERSAL" "Unicode::Collate" "Unicode::Normalize" "Unicode::UCD"
"User::grent" "User::pwent" "Win32::DBIODBC" "XML::Parser"
"XML::Parser::Expat" "XML::Parser::Style::Debug"
"XML::Parser::Style::Objects" "XML::Parser::Style::Stream"
"XML::Parser::Style::Subs" "XML::Parser::Style::Tree" "XSLoader" "a2p"
"attributes" "attrs" "autodie" "autodie::exception"
"autodie::exception::system" "autodie::hints" "autouse" "base" "bigint"
"bignum" "bigrat" "blib" "bytes" "charnames" "constant" "diagnostics"
"encoding" "encoding::warnings" "feature" "fields" "filetest" "if"
"integer" "less" "lib" "locale" "maatkit" "mach::B" "mach::B::Concise"
"mach::B::Debug" "mach::B::Deparse" "mach::B::Lint" "mach::B::Showlex"
"mach::B::Terse" "mach::B::Xref" "mach::Bundle::DBD::mysql"
"mach::Bundle::DBI" "mach::Compress::Raw::Bzip2"
"mach::Compress::Raw::Zlib" "mach::Compress::Zlib" "mach::Config"
"mach::Cwd" "mach::DBD::DBM" "mach::DBD::ExampleP" "mach::DBD::File"
"mach::DBD::File::Developers" "mach::DBD::File::HowTo"
"mach::DBD::File::Roadmap" "mach::DBD::Gofer"
"mach::DBD::Gofer::Policy::Base" "mach::DBD::Gofer::Policy::classic"
"mach::DBD::Gofer::Policy::pedantic" "mach::DBD::Gofer::Policy::rush"
"mach::DBD::Gofer::Transport::Base" "mach::DBD::Gofer::Transport::null"
"mach::DBD::Gofer::Transport::pipeone"
"mach::DBD::Gofer::Transport::stream" "mach::DBD::NullP" "mach::DBD::Proxy"
"mach::DBD::Sponge" "mach::DBD::mysql" "mach::DBD::mysql::GetInfo"
"mach::DBD::mysql::INSTALL" "mach::DBI" "mach::DBI::Changes"
"mach::DBI::Const::GetInfo::ANSI" "mach::DBI::Const::GetInfo::ODBC"
"mach::DBI::Const::GetInfoReturn" "mach::DBI::Const::GetInfoType"
"mach::DBI::DBD" "mach::DBI::DBD::Metadata" "mach::DBI::DBD::SqlEngine"
"mach::DBI::DBD::SqlEngine::Developers" "mach::DBI::DBD::SqlEngine::HowTo"
"mach::DBI::FAQ" "mach::DBI::Gofer::Execute" "mach::DBI::Gofer::Request"
"mach::DBI::Gofer::Response" "mach::DBI::Gofer::Serializer::Base"
"mach::DBI::Gofer::Serializer::DataDumper"
"mach::DBI::Gofer::Serializer::Storable"
"mach::DBI::Gofer::Transport::Base" "mach::DBI::Gofer::Transport::pipeone"
"mach::DBI::Gofer::Transport::stream" "mach::DBI::Profile"
"mach::DBI::ProfileData" "mach::DBI::ProfileDumper"
"mach::DBI::ProfileDumper::Apache" "mach::DBI::ProfileSubs"
"mach::DBI::ProxyServer" "mach::DBI::PurePerl" "mach::DBI::SQL::Nano"
"mach::DBI::Util::CacheMemory" "mach::DBI::Util::_accessor"
"mach::DBI::W32ODBC" "mach::DB_File" "mach::Data::Dumper"
"mach::Devel::DProf" "mach::Devel::PPPort" "mach::Devel::Peek"
"mach::Digest::MD5" "mach::Digest::SHA" "mach::DynaLoader" "mach::Encode"
"mach::Encode::Alias" "mach::Encode::Byte" "mach::Encode::CJKConstants"
"mach::Encode::CN" "mach::Encode::CN::HZ" "mach::Encode::Config"
"mach::Encode::EBCDIC" "mach::Encode::Encoder" "mach::Encode::Encoding"
"mach::Encode::GSM0338" "mach::Encode::Guess" "mach::Encode::JP"
"mach::Encode::JP::H2Z" "mach::Encode::JP::JIS7" "mach::Encode::KR"
"mach::Encode::KR::2022_KR" "mach::Encode::MIME::Header"
"mach::Encode::MIME::Header::ISO_2022_JP" "mach::Encode::MIME::Name"
"mach::Encode::Symbol" "mach::Encode::TW" "mach::Encode::Unicode"
"mach::Encode::Unicode::UTF7" "mach::Errno" "mach::Fcntl"
"mach::File::Glob" "mach::File::GlobMapper" "mach::Filter::Util::Call"
"mach::Hash::Util" "mach::Hash::Util::FieldHash" "mach::I18N::Langinfo"
"mach::IO" "mach::IO::Compress::Adapter::Bzip2"
"mach::IO::Compress::Adapter::Deflate"
"mach::IO::Compress::Adapter::Identity" "mach::IO::Compress::Base"
"mach::IO::Compress::Base::Common" "mach::IO::Compress::Bzip2"
"mach::IO::Compress::Deflate" "mach::IO::Compress::Gzip"
"mach::IO::Compress::Gzip::Constants" "mach::IO::Compress::RawDeflate"
"mach::IO::Compress::Zip" "mach::IO::Compress::Zip::Constants"
"mach::IO::Compress::Zlib::Constants" "mach::IO::Compress::Zlib::Extra"
"mach::IO::Dir" "mach::IO::File" "mach::IO::Handle" "mach::IO::Pipe"
"mach::IO::Poll" "mach::IO::Seekable" "mach::IO::Select" "mach::IO::Socket"
"mach::IO::Socket::INET" "mach::IO::Socket::UNIX"
"mach::IO::Uncompress::Adapter::Bunzip2"
"mach::IO::Uncompress::Adapter::Identity"
"mach::IO::Uncompress::Adapter::Inflate" "mach::IO::Uncompress::AnyInflate"
"mach::IO::Uncompress::AnyUncompress" "mach::IO::Uncompress::Base"
"mach::IO::Uncompress::Bunzip2" "mach::IO::Uncompress::Gunzip"
"mach::IO::Uncompress::Inflate" "mach::IO::Uncompress::RawInflate"
"mach::IO::Uncompress::Unzip" "mach::IPC::Msg" "mach::IPC::Semaphore"
"mach::IPC::SharedMem" "mach::IPC::SysV" "mach::Irssi" "mach::Irssi::Irc"
"mach::Irssi::TextUI" "mach::Irssi::UI" "mach::List::Util"
"mach::List::Util::PP" "mach::List::Util::XS" "mach::Locale::gettext"
"mach::MIME::Base64" "mach::MIME::QuotedPrint"
"mach::Math::BigInt::FastCalc" "mach::NDBM_File" "mach::Net::SSLeay"
"mach::Net::SSLeay::Handle" "mach::NetSNMP::ASN" "mach::NetSNMP::OID"
"mach::NetSNMP::TrapReceiver" "mach::NetSNMP::agent"
"mach::NetSNMP::agent::Support" "mach::NetSNMP::agent::default_store"
"mach::NetSNMP::agent::netsnmp_request_infoPtr"
"mach::NetSNMP::default_store" "mach::O" "mach::Opcode" "mach::POSIX"
"mach::PerlIO::encoding" "mach::PerlIO::scalar" "mach::PerlIO::via"
"mach::RRDs" "mach::SDBM_File" "mach::SNMP" "mach::Scalar::Util"
"mach::Scalar::Util::PP" "mach::Socket" "mach::Socket6" "mach::Storable"
"mach::Sys::Hostname" "mach::Sys::Syslog" "mach::Term::ReadKey"
"mach::Text::Soundex" "mach::Time::HiRes" "mach::Time::Piece"
"mach::Time::Seconds" "mach::Unicode::Normalize" "mach::Win32::DBIODBC"
"mach::XML::Parser" "mach::XML::Parser::Expat"
"mach::XML::Parser::Style::Debug" "mach::XML::Parser::Style::Objects"
"mach::XML::Parser::Style::Stream" "mach::XML::Parser::Style::Subs"
"mach::XML::Parser::Style::Tree" "mach::XSLoader" "mach::attrs"
"mach::encoding" "mach::lib" "mach::mro" "mach::ops" "mach::re"
"mach::threads" "mach::threads::shared" "mro" "open.pod" "ops" "overload"
"overload::numbers" "overloading" "parent" "perl" "perl5004delta"
"perl5005delta" "perl5100delta" "perl5101delta" "perl561delta"
"perl56delta" "perl570delta" "perl571delta" "perl572delta" "perl573delta"
"perl581delta" "perl582delta" "perl583delta" "perl584delta" "perl585delta"
"perl586delta" "perl587delta" "perl588delta" "perl589delta" "perl58delta"
"perl590delta" "perl591delta" "perl592delta" "perl593delta" "perl594delta"
"perl595delta" "perlaix" "perlamiga" "perlapi" "perlapio" "perlapollo"
"perlartistic" "perlbeos" "perlbook" "perlboot" "perlbot" "perlbs2000"
"perlcall" "perlce" "perlcheat" "perlclib" "perlcn" "perlcommunity"
"perlcompile" "perlcygwin" "perldata" "perldbmfilter" "perldebguts"
"perldebtut" "perldebug" "perldelta" "perldgux" "perldiag" "perldoc"
"perldos" "perldsc" "perlebcdic" "perlembed" "perlepoc" "perlfaq"
"perlfaq1" "perlfaq2" "perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6"
"perlfaq7" "perlfaq8" "perlfaq9" "perlfilter" "perlfork" "perlform"
"perlfreebsd" "perlfunc" "perlglossary" "perlgpl" "perlguts" "perlhack"
"perlhaiku" "perlhist" "perlhpux" "perlhurd" "perlintern" "perlintro"
"perliol" "perlipc" "perlirix" "perljp" "perlko" "perllexwarn" "perllinux"
"perllocale" "perllol" "perlmachten" "perlmacos" "perlmacosx" "perlmint"
"perlmod" "perlmodinstall" "perlmodlib" "perlmodstyle" "perlmpeix"
"perlmroapi" "perlnetware" "perlnewmod" "perlnumber" "perlobj" "perlop"
"perlopenbsd" "perlopentut" "perlos2" "perlos390" "perlos400" "perlothrtut"
"perlpacktut" "perlperf" "perlplan9" "perlpod" "perlpodspec" "perlport"
"perlpragma" "perlqnx" "perlre" "perlreapi" "perlrebackslash"
"perlrecharclass" "perlref" "perlreftut" "perlreguts" "perlrepository"
"perlrequick" "perlreref" "perlretut" "perlriscos" "perlrun" "perlsec"
"perlsolaris" "perlstyle" "perlsub" "perlsymbian" "perlsyn" "perlthrtut"
"perltie" "perltoc" "perltodo" "perltooc" "perltoot" "perltrap" "perltru64"
"perltw" "perlunicode" "perlunifaq" "perluniintro" "perlunitut" "perlutil"
"perluts" "perlvar" "perlvmesa" "perlvms" "perlvos" "perlwin32" "perlxs"
"perlxstut" "re" "sigtrap" "sort.pod" "strict" "subs" "threads"
"threads::shared" "utf8" "vars" "version" "version::Internals" "vmsish"
"warnings" "warnings::register"))
